routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CollectionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::redirect('/products', '/collections');
Route::get('/collections', [CollectionController::class, 'listCollections'])->name('list-collection');
Route::get('/collections/{collection-slug}', [CollectionController::class, 'index'])->name('collections');

Route::get('/products/{product-slug}', [CollectionController::class, 'index'])->name('products');
Route::get('/collections/{collection-slug}/products/{product-slug}', [CollectionController::class, 'index'])->name('collections-products');

Route::get('/dashboard', function () {
  return view('pages.dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


Route::group(['prefix' => 'admin'], function () {
  Voyager::routes();
});

Route::get('/clear-cache', function () {
  Artisan::call('cache:clear');
  return "Cache is cleared";
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
      return view('layouts.app');
    }
}

resources/views/pages/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/pages/home.blade.php
@once
  @push('head scripts')
    <script src="{{ asset('js/plugins/swiper-bundle.min.js') }}"></script>
  @endpush
@endonce

@once
  @push('styles')
    <link rel="stylesheet" href="{{ asset('css/plugins/swiper-bundle.min.css') }}">
  @endpush
@endonce

<x-app-layout>

  <x-home-banner :photos="$photos"></x-home-banner>


  <section class="home-list-conllection py-12">
    <x-container>
      <div class="grid gap-6 grid-cols-6 grid-rows-2">
        {{-- $collections limit 3 value --}}
        @foreach ($collections as $collection)
          @if ($loop->first)
            <div class="col-span-6 md:col-span-3 md:row-span-2 lg:col-span-2 group">
              <a href="{{ route('collections', $collection->slug) }}" class="relative block pb-[125%] overflow-hidden">
          @elseif ($loop->last)
            <div class="col-span-3 md:row-span-1 lg:col-span-2 lg:row-span-2 group">
              <a href="{{ route('collections', $collection->slug) }}" class="relative block pb-[125%] md:pb-[calc(62.5%-12px)] lg:pb-[125%] overflow-hidden">
          @else
            <div class="col-span-3 md:row-span-1 lg:col-span-2 lg:row-span-2 group">
              <a href="{{ route('collections', $collection->slug) }}" class="relative block pb-[125%] md:pb-[calc(62.5%-12px)] lg:pb-[125%] overflow-hidden">
          @endif

                <div class="absolute w-full h-full top-0 left-0 group-hover:scale-150 transition-transform duration-75 group-hover:duration-[5s] ease-linear">
                  <img src="{{ Voyager::image($collection->getImage())}}" alt="" class="w-full h-full object-cover" loading="lazy">
                </div>

                <div class="absolute w-full h-full top-0 left-0 transition-colors duration-300 ease-in-out group-hover:bg-black/70 pointer-events-none flex items-end px-4 py-10">
                  <h2 class="text-3xl font-bold uppercase text-white">{{ $collection->title }}</h2>
                </div>
              </a>
            </div>
        @endforeach
      </div>
    </x-container>
  </section>


  <section class="doi-tac">
    <x-container>
      <div class="">Đối tác của chúng tôi</div>
    </x-container>
  </section>
</x-app-layout>